import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const cormorant = Cormorant_Garamond({ subsets: ["latin"], variable: "--font-cormorant" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Product Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full bg-white",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        inter.variable,
        cormorant.variable,
        "font-sans",
      )}
    >
      <body className="font-inter" cz-shortcut-listen="false">
        <div vaul-drawer-wrapper="" className="w-full max-w-sm min-h-dvh h-full mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
